# Generated by Django 5.1.3 on 2024-11-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='signature',
            field=models.TextField(),
        ),
    ]
