# Generated by Django 5.1.3 on 2024-11-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_alter_record_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signature/'),
        ),
    ]
