# Generated by Django 5.1.3 on 2024-11-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_alter_record_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
